### PR TITLE
Using context

### PR DESCRIPTION
**Pull request by ItumelengKekana**
### What the PR does

- Merges into the main branch the `state management feature`

### Description of task to be completed

- created a file for context component

- moved addToCart and removeFromCart to context

- moved types to separate file

- added comments to explain type definitions and functions

### Ticket

- Typescript with useContext

### Ticket ID

- WHP-105

### PR

- Delivers a feature

### CODE REVIEW

**Review by Plnyakan — APPROVED** [review]

**Comment by jamesbeamie** [comment]
- Make sure the `PR` is in the standard format
- You don't have to take screenshot of code(Just screenshot the UI)

**Comment by jamesbeamie** [comment]
Screenshot 2022-05-11 at 11 34 41

**Comment by jamesbeamie** [comment]
- Everything has to be similar to the screenshot above, 
- You can refer to this `PR` `https://github.com/jamesbeamie/git-flow/pull/1`

**Comment by jamesbeamie** [comment]
- `PR` name must follow the format `Feature(sub-feature): what you have exactly worked on`
- (e.g) Authentication(Signup):Input form

**Review by Vgovender — APPROVED** [review]
Looks Great!

**Pull request merged**
